a = int(input("Digite o primeiro valor: "))
b = int(input("Digite o segundo valor: "))

print("\nResultados:")
print(f"a > b: {a > b}")
print(f"a < b: {a < b}")
print(f"a >= b: {a >= b}")
print(f"a <= b: {a <= b}")
print(f"a == b: {a == b}")
print(f"a != b: {a != b}")